# Minimal wrapper image around FreeSurfer that includes mideface + mri_convert

FROM freesurfer/freesurfer:7.4.1

ENV FREESURFER_HOME=/usr/local/freesurfer
ENV PATH=${FREESURFER_HOME}/bin:${PATH}

WORKDIR /work